// ff-data.js — Fridge Finder recipe bank & lookup tables
// Loaded before ff-engine.js. No DOM or app-global references here.

// ════════════════════════════════════════════════════════════════════
// FRIDGE FINDER — local recipe engine
// ════════════════════════════════════════════════════════════════════

// ── Ingredient normaliser & synonyms ───────────────────────────────
var FF_NORM_MAP = {
  'baby marrow':'courgette','zucchini':'courgette',
  'capsicum':'bell pepper','green pepper':'bell pepper','red pepper':'bell pepper','yellow pepper':'bell pepper',
  'mince':'ground beef','beef mince':'ground beef','minced beef':'ground beef','lamb mince':'ground beef',
  'tinned tomatoes':'canned tomatoes','tin tomatoes':'canned tomatoes','chopped tomatoes':'canned tomatoes',
  'crushed tomatoes':'canned tomatoes','canned tomato':'canned tomatoes',
  'boerewors':'sausage','wors':'sausage','viennas':'sausage','boerie':'sausage',
  'naartjie':'tangerine','mandarin':'tangerine',
  'gem squash':'squash','butternut squash':'squash','butternut':'squash',
  'dhania':'coriander','cilantro':'coriander','fresh coriander':'coriander',
  'chili':'chilli','chile':'chilli','fresh chilli':'chilli','dried chilli':'chilli',
  'scallions':'spring onions','green onions':'spring onions',
  'mieliepap':'maize meal','pap':'maize meal','mealie meal':'maize meal',
  'corn meal':'maize meal','polenta':'maize meal',
  'raisins':'dried fruit','sultanas':'dried fruit',
  'double cream':'cream','single cream':'cream','fresh cream':'cream','whipping cream':'cream',
  'plain flour':'flour','self raising flour':'flour','bread flour':'flour',
  'canola oil':'oil','sunflower oil':'oil','vegetable oil':'oil','olive oil':'oil','cooking oil':'oil',
  'lemon juice':'lemon',
  'tin beans':'beans','canned beans':'beans','tinned beans':'beans',
  'kidney beans':'beans','baked beans':'beans','chickpeas':'beans','cannellini beans':'beans',
  'baby spinach':'spinach','spinach leaves':'spinach',
  'cherry tomatoes':'tomatoes','roma tomatoes':'tomatoes','plum tomatoes':'tomatoes',
  'brown onion':'onion','white onion':'onion','red onion':'onion',
  'sweet potato':'sweet potatoes',
  'chicken breast':'chicken','chicken thigh':'chicken','chicken thighs':'chicken',
  'chicken drumstick':'chicken','chicken pieces':'chicken',
  'beef steak':'steak','rump steak':'steak','sirloin steak':'steak',
  'minced garlic':'garlic','garlic cloves':'garlic','garlic clove':'garlic',
  'whole milk':'milk','skim milk':'milk','fat free milk':'milk',
  'cheddar cheese':'cheese','mozzarella':'cheese','feta':'cheese','gouda':'cheese',
  'penne':'pasta','spaghetti':'pasta','fusilli':'pasta','linguine':'pasta','macaroni':'pasta',
  'basmati rice':'rice','jasmine rice':'rice','white rice':'rice','brown rice':'rice',
  'bread rolls':'bread','white bread':'bread','brown bread':'bread',
  'salted butter':'butter','unsalted butter':'butter',
  'apple cider vinegar':'vinegar','white vinegar':'vinegar','red wine vinegar':'vinegar',
  'beef stock':'stock','chicken stock':'stock','vegetable stock':'stock',
  'soy sauce':'soy',
  'snoek':'fish','kabeljou':'fish','hake':'fish','yellowtail':'fish',
  'noodles':'pasta','egg noodles':'pasta','rice noodles':'pasta',
  'avocado':'avocado','avo':'avocado',
  'rashers':'bacon','streaky bacon':'bacon',
  'peas':'peas','frozen peas':'peas','garden peas':'peas',
  'broccoli florets':'broccoli',
  'courgette':'courgette','baby marrow':'courgette',
  'plain yoghurt':'yoghurt','greek yoghurt':'yoghurt','double cream yogurt':'yoghurt',
  'bicarbonate of soda':'bicarb','baking soda':'bicarb',
  'self-raising flour':'flour',
  'tin fish':'tuna',
  // ── W3/W4 Mediterranean & Asian ingredient aliases ──────────────────
  'eggplant':'aubergine','egg plant':'aubergine','brinjal':'aubergine',
  'firm tofu':'tofu','silken tofu':'tofu','soft tofu':'tofu','extra firm tofu':'tofu',
  'soba noodles':'noodles','udon noodles':'noodles','rice vermicelli':'noodles',
  'bulgur':'couscous','bulgur wheat':'couscous','pearl couscous':'couscous',
  'white miso':'miso','red miso':'miso','miso paste':'miso',
  'fresh ginger':'ginger','ground ginger':'ginger','ginger root':'ginger',
  'tamari':'soy','light soy sauce':'soy','dark soy sauce':'soy',
  'coconut cream':'coconut milk','light coconut milk':'coconut milk',
  'chia':'chia seeds','black chia':'chia seeds',
  'sesame seeds':'sesame','toasted sesame':'sesame','sesame seed':'sesame',
  'tahini paste':'tahini',
  'halloumi cheese':'halloumi',
  'curry paste':'red curry paste','thai curry paste':'red curry paste','green curry paste':'red curry paste',
  'nori sheet':'nori','nori sheets':'nori','seaweed':'nori','dried seaweed':'nori',
  'edamame beans':'edamame','frozen edamame':'edamame','shelled edamame':'edamame',
  'tamarind paste':'tamarind','tamarind sauce':'tamarind','tamarind concentrate':'tamarind',
  'quinoa flakes':'quinoa','red quinoa':'quinoa','white quinoa':'quinoa',
  'ras el hanout':'ras el hanout','harissa':'harissa',
  'truffle oil':'truffle oil',
};

function ffNorm(s) {
  var n = s.toLowerCase().trim().replace(/\s+/g,' ');
  return FF_NORM_MAP[n] || n;
}
function ffIngMatch(available, recipeIng) {
  var ra = ffNorm(recipeIng);
  return available.some(function(a) {
    var aa = ffNorm(a);
    return aa === ra || ra.indexOf(aa) !== -1 || aa.indexOf(ra) !== -1;
  });
}
function ffParseInput(str) {
  return str.split(/[,\n]+/).map(function(s){ return s.trim(); }).filter(Boolean);
}

// ── Category definitions ────────────────────────────────────────────
var FF_CATS = [
  {k:'all',       l:'All Recipes',    e:'🍽'},
  {k:'quick',     l:'Quick ≤20 min',  e:'⚡'},
  {k:'onepot',    l:'One-Pot',        e:'🍲'},
  {k:'protein',   l:'High Protein',   e:'💪'},
  {k:'sa',        l:'SA Classics',    e:'🇿🇦'},
  {k:'breakfast', l:'Brekkie',        e:'🍳'},
  {k:'budget',    l:'Budget',         e:'💰'},
  {k:'lunchbox',  l:'Lunchbox',       e:'🥡'},
  {k:'crowd',     l:'Weekend',        e:'🎉'},
  {k:'med',       l:'Mediterranean',  e:'🫒'},
  {k:'asian',     l:'Asian Kitchen',  e:'🥢'}
];

// ── Pantry quick-tap chips ──────────────────────────────────────────
var FF_PANTRY_CHIPS = [
  'eggs','onion','garlic','tomatoes','chicken','mince','steak',
  'rice','pasta','potatoes','sweet potatoes','cheese','milk','butter',
  'flour','oil','lemon','spinach','canned tomatoes','avocado',
  'beans','lentils','bread','cream','soy sauce','stock',
  'bacon','carrots','broccoli','bell pepper','peas','noodles',
  'tahini','halloumi','tofu','couscous','quinoa','miso',
  'coconut milk','edamame','chia seeds','nori','aubergine','ginger',
  'red curry paste','sesame','olives'
];

// ── Recipe bank (100 recipes) ───────────────────────────────────────
// Fields: id, n=name, c=cat, e=emoji, t=time(min), s=serves,
//         tags=[], ing=[], steps=[]
var FF_RECIPES = [

// ── QUICK WEEKNIGHT ≤20 min ─────────────────────────────────────────
{id:'qw01',n:'Pesto Pasta',c:'quick',e:'🍝',t:15,s:4,tags:['v'],p:14,
 ing:['pasta','pesto','parmesan','cherry tomatoes','olive oil'],
 steps:['Cook pasta al dente per packet instructions.',
        'Drain, reserving a splash of pasta water.',
        'Toss with pesto, pasta water and olive oil until glossy.',
        'Top with halved cherry tomatoes and grated parmesan.']},

{id:'qw02',n:'Egg Fried Rice',c:'quick',e:'🍳',t:15,s:4,tags:['v','gf'],p:12,
 ing:['rice','eggs','soy sauce','oil','spring onions','frozen peas'],
 steps:['Use cold day-old rice for best results.',
        'Heat oil in a wok on high. Scramble eggs and push to side.',
        'Add rice, stir-fry 3 min. Add peas and soy sauce.',
        'Toss to combine. Top with sliced spring onions.']},

{id:'qw03',n:'Toasted Cheese & Tomato',c:'quick',e:'🧀',t:10,s:2,tags:['v'],p:14,
 ing:['bread','cheese','tomatoes','butter','salt'],
 steps:['Butter bread slices on outside.',
        'Layer cheese and sliced tomatoes on inside.',
        'Pan-fry on medium until golden and cheese melts.',
        'Serve with a pinch of salt and black pepper.']},

{id:'qw04',n:'Tuna Pasta',c:'quick',e:'🐟',t:18,s:4,tags:['df'],p:26,
 ing:['pasta','tuna','canned tomatoes','onion','garlic','olive oil'],
 steps:['Cook pasta al dente.',
        'Sauté onion and garlic in olive oil 3 min.',
        'Add canned tomatoes, simmer 5 min. Stir in drained tuna.',
        'Toss pasta in sauce. Season well.']},

{id:'qw05',n:'Stir-Fried Noodles',c:'quick',e:'🍜',t:15,s:4,tags:['v'],p:11,
 ing:['noodles','soy sauce','oil','cabbage','carrots','eggs','sesame oil'],
 steps:['Cook noodles per packet. Drain and set aside.',
        'Stir-fry shredded cabbage and julienned carrots 3 min.',
        'Add noodles, soy sauce and a drizzle of sesame oil.',
        'Push aside, scramble eggs in the pan, then fold everything together.']},

{id:'qw06',n:'Greek Salad with Pita',c:'quick',e:'🥗',t:10,s:4,tags:['v'],p:12,
 ing:['tomatoes','cucumber','feta','olives','onion','olive oil','pita bread'],
 steps:['Dice tomatoes and cucumber. Slice onion thinly.',
        'Combine with olives and crumbled feta.',
        'Dress with olive oil, salt and oregano.',
        'Warm pita in a dry pan and serve alongside.']},

{id:'qw07',n:'Cheese Omelette',c:'quick',e:'🍳',t:10,s:2,tags:['v','gf'],p:15,
 ing:['eggs','cheese','butter','salt','milk'],
 steps:['Whisk eggs with a splash of milk, salt and pepper.',
        'Melt butter in non-stick pan on medium heat.',
        'Pour in eggs; let edges set, then lift and tilt.',
        'Add grated cheese, fold in half and serve immediately.']},

{id:'qw08',n:'Bean & Veg Wrap',c:'quick',e:'🌯',t:12,s:4,tags:['v'],p:11,
 ing:['wraps','beans','tomatoes','cheese','lettuce','sour cream','onion'],
 steps:['Warm beans in pan with cumin and salt.',
        'Layer warm tortillas with beans, diced tomatoes, cheese.',
        'Add shredded lettuce and a dollop of sour cream.',
        'Roll tightly and slice in half.']},

{id:'qw09',n:'Quick Chicken Stir-Fry',c:'quick',e:'🥘',t:18,s:4,tags:['gf','hf'],p:30,
 ing:['chicken','broccoli','bell pepper','soy sauce','garlic','oil','cornflour'],
 steps:['Slice chicken thin. Toss in cornflour, salt and pepper.',
        'Stir-fry chicken in hot oil until golden, remove.',
        'Fry garlic, broccoli and bell pepper 3 min.',
        'Return chicken, add soy sauce and toss to coat.']},

{id:'qw10',n:'Avocado Eggs on Toast',c:'quick',e:'🥑',t:12,s:2,tags:['v'],p:14,
 ing:['bread','avocado','eggs','lemon','salt','chilli'],
 steps:['Toast bread slices until golden.',
        'Mash avocado with lemon juice, salt and chilli.',
        'Fry or poach eggs to your liking.',
        'Spread avocado on toast and top with egg.']},

{id:'qw11',n:'Pan-Fried Boerewors & Mash',c:'quick',e:'🌭',t:20,s:4,tags:[],p:22,
 ing:['sausage','potatoes','butter','milk','onion','oil'],
 steps:['Boil potatoes until tender. Mash with butter, milk and salt.',
        'Pan-fry boerewors in a little oil on medium heat, turning often.',
        'Slice onions and fry until caramelised for a quick gravy base.',
        'Serve sausage on mash with onions.']},

{id:'qw12',n:'Quick Tomato Pasta',c:'quick',e:'🍅',t:18,s:4,tags:['v'],p:11,
 ing:['pasta','canned tomatoes','garlic','olive oil','basil','parmesan'],
 steps:['Cook pasta al dente.',
        'Gently simmer crushed garlic in olive oil 1 min.',
        'Add canned tomatoes, season and simmer 8 min.',
        'Toss with pasta and fresh basil. Finish with parmesan.']},

{id:'qw13',n:'Sardines on Toast',c:'quick',e:'🐟',t:8,s:2,tags:['df','gf'],p:20,
 ing:['sardines','bread','lemon','tomatoes','black pepper'],
 steps:['Toast bread until crisp.',
        'Open and drain sardines, lay on toast.',
        'Top with sliced tomatoes, squeeze of lemon.',
        'Grind black pepper generously over the top.']},

{id:'qw14',n:'Scrambled Eggs on Toast',c:'quick',e:'🍳',t:10,s:2,tags:['v'],p:13,
 ing:['eggs','butter','milk','bread','salt'],
 steps:['Whisk eggs with a splash of milk, salt and pepper.',
        'Melt butter in pan on low-medium heat.',
        'Add eggs, stir slowly and continuously until just set.',
        'Serve immediately on hot buttered toast.']},

{id:'qw15',n:'Speedy Quesadillas',c:'quick',e:'🫓',t:12,s:2,tags:['v'],p:14,
 ing:['wraps','cheese','bell pepper','onion','butter','sour cream'],
 steps:['Sauté diced onion and pepper 3 min.',
        'Fill one tortilla with cheese and veg. Top with second tortilla.',
        'Cook in buttered pan 2 min each side until golden.',
        'Cut into wedges, serve with sour cream.']},

// ── ONE-POT / TRAY BAKES ────────────────────────────────────────────
{id:'op01',n:'Chicken & Rice One-Pot',c:'onepot',e:'🍗',t:45,s:4,tags:['gf','hf'],p:30,
 ing:['chicken','rice','onion','garlic','stock','canned tomatoes','paprika'],
 steps:['Brown chicken pieces in a heavy pot. Remove and set aside.',
        'Sauté onion and garlic until soft. Add paprika.',
        'Stir in rice, add stock and canned tomatoes.',
        'Return chicken, cover and simmer 25 min until rice is cooked.']},

{id:'op02',n:'Vegetable Curry',c:'onepot',e:'🍛',t:35,s:4,tags:['v','vg','gf'],p:12,
 ing:['potatoes','carrots','onion','canned tomatoes','curry powder','garlic','oil','chickpeas'],
 steps:['Fry onion and garlic in oil until soft.',
        'Add curry powder, stir 1 min until fragrant.',
        'Add potatoes, carrots, chickpeas and canned tomatoes.',
        'Cover and simmer 20 min until vegetables are tender.']},

{id:'op03',n:'Hearty Beef Stew',c:'onepot',e:'🥩',t:90,s:6,tags:['gf'],p:28,
 ing:['steak','potatoes','carrots','onion','stock','canned tomatoes','garlic','flour'],
 steps:['Brown beef cubes (dusted in flour) in batches. Set aside.',
        'Fry onion and garlic until soft.',
        'Return beef, add stock, canned tomatoes, potatoes and carrots.',
        'Cover and simmer 60 min until beef is fall-apart tender.']},

{id:'op04',n:'Red Lentil Soup',c:'onepot',e:'🍜',t:30,s:6,tags:['v','vg','gf'],p:14,
 ing:['lentils','onion','garlic','canned tomatoes','cumin','stock','oil'],
 steps:['Fry onion and garlic in oil until golden.',
        'Add cumin, stir 30 sec. Add lentils, canned tomatoes and stock.',
        'Bring to boil then simmer 20 min until lentils are soft.',
        'Blend half the soup for a thick, creamy texture. Season well.']},

{id:'op05',n:'Butter Bean Tomato Stew',c:'onepot',e:'🫘',t:25,s:4,tags:['v','vg','gf'],p:11,
 ing:['beans','canned tomatoes','garlic','onion','olive oil','spinach','smoked paprika'],
 steps:['Fry onion and garlic in olive oil 4 min.',
        'Add smoked paprika, stir 30 sec.',
        'Add canned tomatoes and butter beans. Simmer 12 min.',
        'Stir in spinach until wilted. Season and serve with crusty bread.']},

{id:'op06',n:'Roasted Veg Tray Bake',c:'onepot',e:'🥦',t:40,s:4,tags:['v','vg','gf'],p:10,
 ing:['sweet potatoes','broccoli','bell pepper','onion','olive oil','garlic','feta'],
 steps:['Preheat oven to 200°C.',
        'Chop all veg into chunks. Toss with olive oil, garlic, salt and pepper.',
        'Spread on a large tray. Roast 30 min, turning halfway.',
        'Crumble feta over and return to oven 5 min.']},

{id:'op07',n:'Chicken Tray Bake',c:'onepot',e:'🍗',t:50,s:4,tags:['gf','hf'],p:28,
 ing:['chicken','potatoes','onion','garlic','olive oil','paprika','lemon','rosemary'],
 steps:['Preheat oven to 200°C.',
        'Toss chunked potatoes and onion with oil, paprika and salt.',
        'Nestle chicken pieces on top. Squeeze over lemon, scatter rosemary.',
        'Roast 40 min until chicken is golden and juices run clear.']},

{id:'op08',n:'One-Pot Pasta Primavera',c:'onepot',e:'🍝',t:25,s:4,tags:['v'],p:14,
 ing:['pasta','broccoli','bell pepper','onion','garlic','cream','parmesan','butter'],
 steps:['Sauté onion and garlic in butter 3 min.',
        'Add cream and bring to a gentle simmer.',
        'Add pasta and just enough water to cover; cook 10 min stirring often.',
        'Fold in broccoli and bell pepper. Cook 4 min. Finish with parmesan.']},

{id:'op09',n:'Mince & Veg Casserole',c:'onepot',e:'🥘',t:50,s:6,tags:[],p:26,
 ing:['ground beef','potatoes','carrots','onion','canned tomatoes','garlic','stock'],
 steps:['Brown mince in a large pot, breaking it up. Drain excess fat.',
        'Add onion and garlic; fry 3 min.',
        'Stir in diced potatoes, carrots, canned tomatoes and stock.',
        'Simmer covered 30 min until veg is tender. Season generously.']},

{id:'op10',n:'Sweet Potato & Chickpea Curry',c:'onepot',e:'🍛',t:35,s:4,tags:['v','vg','gf'],p:12,
 ing:['sweet potatoes','beans','canned tomatoes','onion','garlic','curry powder','coconut milk','oil'],
 steps:['Fry onion and garlic until soft.',
        'Add curry powder, stir 1 min.',
        'Add diced sweet potato, chickpeas, canned tomatoes and coconut milk.',
        'Simmer 25 min until sweet potato is soft. Serve with rice.']},

{id:'op11',n:'Shakshuka',c:'onepot',e:'🍳',t:25,s:4,tags:['v','gf'],p:14,
 ing:['eggs','canned tomatoes','bell pepper','onion','garlic','cumin','paprika','oil'],
 steps:['Fry onion and pepper in oil until soft.',
        'Add garlic, cumin and paprika. Cook 1 min.',
        'Pour in canned tomatoes. Simmer 10 min until slightly thickened.',
        'Create wells and crack in eggs. Cover and cook 7 min until whites set.']},

{id:'op12',n:'Sausage & Veg Tray Bake',c:'onepot',e:'🌭',t:45,s:4,tags:[],p:22,
 ing:['sausage','potatoes','onion','bell pepper','olive oil','garlic','mustard'],
 steps:['Preheat oven to 200°C.',
        'Parboil potato chunks 5 min. Drain.',
        'Toss potatoes, sliced sausage, onion and pepper with oil and mustard.',
        'Spread on tray, roast 30 min turning once.']},

{id:'op13',n:'Vegetarian Bean Chilli',c:'onepot',e:'🌶',t:40,s:6,tags:['v','vg','gf'],p:11,
 ing:['beans','canned tomatoes','onion','garlic','bell pepper','chilli','cumin','oil'],
 steps:['Fry onion, garlic and bell pepper in oil until soft.',
        'Add chilli, cumin, stir 1 min.',
        'Add beans and canned tomatoes. Season with salt.',
        'Simmer 25 min until thick. Serve with rice or bread.']},

{id:'op14',n:'Tomato Braised Chicken',c:'onepot',e:'🍗',t:45,s:4,tags:['gf'],p:28,
 ing:['chicken','canned tomatoes','onion','garlic','olive oil','basil','stock'],
 steps:['Brown chicken in olive oil. Remove and set aside.',
        'Fry onion and garlic 3 min.',
        'Add canned tomatoes, stock and basil. Stir well.',
        'Return chicken, cover and braise 30 min until cooked through.']},

{id:'op15',n:'Butternut & Lentil Soup',c:'onepot',e:'🎃',t:35,s:6,tags:['v','vg','gf'],p:13,
 ing:['squash','lentils','onion','garlic','stock','cumin','oil','cream'],
 steps:['Fry onion and garlic in oil. Add cumin.',
        'Add cubed butternut, lentils and stock.',
        'Simmer 25 min until everything is soft.',
        'Blend until smooth. Stir in cream, season and serve.']},

// ── CJ PROTEIN MEALS ────────────────────────────────────────────────
{id:'pr01',n:'Grilled Chicken & Veg',c:'protein',e:'💪',t:20,s:2,tags:['gf','hf'],p:38,
 ing:['chicken','broccoli','carrots','olive oil','garlic','salt','lemon'],
 steps:['Season chicken with salt, pepper and garlic.',
        'Grill or pan-fry on medium-high, 6-7 min each side.',
        'Steam broccoli and carrots until just tender.',
        'Serve with a squeeze of lemon.']},

{id:'pr02',n:'Beef Mince Rice Bowl',c:'protein',e:'🥩',t:20,s:2,tags:['gf','hf'],p:30,
 ing:['ground beef','rice','soy sauce','garlic','onion','oil','sesame oil'],
 steps:['Cook rice per packet.',
        'Brown mince with onion and garlic, breaking up lumps.',
        'Add soy sauce and a splash of sesame oil.',
        'Serve mince over rice. Top with spring onions if available.']},

{id:'pr03',n:'Chicken Meal-Prep Bowls',c:'protein',e:'🍗',t:30,s:4,tags:['gf','hf'],p:36,
 ing:['chicken','rice','sweet potatoes','broccoli','olive oil','garlic','paprika'],
 steps:['Preheat oven to 200°C. Roast sweet potatoes 25 min.',
        'Season and bake chicken breast alongside sweet potato.',
        'Steam broccoli.',
        'Divide rice, chicken, veg into meal-prep containers.']},

{id:'pr04',n:'Pan-Fried Steak & Greens',c:'protein',e:'🥩',t:15,s:2,tags:['gf','hf'],p:34,
 ing:['steak','spinach','garlic','butter','olive oil','salt'],
 steps:['Pat steak dry. Season generously.',
        'Heat oil in cast-iron skillet until smoking. Sear steak 3 min each side.',
        'Add butter and garlic in last minute, baste steak.',
        'Rest 5 min. Wilt spinach in the same pan.']},

{id:'pr05',n:'Tuna Rice Bowl',c:'protein',e:'🐟',t:10,s:2,tags:['gf','hf'],p:28,
 ing:['tuna','rice','soy sauce','lemon','cucumber','spring onions'],
 steps:['Cook rice per packet.',
        'Mix drained tuna with soy sauce and lemon juice.',
        'Slice cucumber into half moons.',
        'Serve tuna over rice, top with cucumber and spring onions.']},

{id:'pr06',n:'Chicken Schnitzel',c:'protein',e:'🍗',t:20,s:4,tags:['hf'],p:36,
 ing:['chicken','flour','eggs','breadcrumbs','oil','lemon','salt'],
 steps:['Flatten chicken breasts between cling wrap.',
        'Coat in flour, then beaten egg, then breadcrumbs.',
        'Shallow fry in hot oil 3-4 min per side until golden.',
        'Drain on paper towel. Serve with lemon wedges.']},

{id:'pr07',n:'Homemade Beef Burger',c:'protein',e:'🍔',t:20,s:4,tags:['hf'],p:28,
 ing:['ground beef','bread','onion','cheese','lettuce','tomatoes','salt'],
 steps:['Season mince with salt and pepper, shape into patties.',
        'Cook on high heat 4 min each side for medium.',
        'Toast burger buns. Layer with cheese, patty, lettuce, tomato.',
        'Add favourite sauce and serve immediately.']},

{id:'pr08',n:'Boiled Egg & Rice Bowl',c:'protein',e:'🥚',t:15,s:2,tags:['v','gf','hf'],p:15,
 ing:['eggs','rice','soy sauce','sesame oil','spring onions','cucumber'],
 steps:['Boil eggs 7 min for jammy yolk. Cool and peel.',
        'Cook rice per packet.',
        'Dress rice with soy sauce and sesame oil.',
        'Halve eggs, serve over rice with sliced cucumber and spring onions.']},

{id:'pr09',n:'Chicken & Pasta',c:'protein',e:'🍝',t:20,s:4,tags:['hf'],p:34,
 ing:['chicken','pasta','garlic','olive oil','parmesan','spinach','lemon'],
 steps:['Cook pasta al dente.',
        'Slice and pan-fry chicken in olive oil until golden.',
        'Add garlic, toss with drained pasta.',
        'Fold in spinach, squeeze lemon. Serve with parmesan.']},

{id:'pr10',n:'Beef Mince Stir-Fry',c:'protein',e:'🥩',t:20,s:4,tags:['hf'],p:28,
 ing:['ground beef','bell pepper','onion','garlic','soy sauce','oil','broccoli'],
 steps:['Brown mince in hot oil, breaking it up. Drain excess fat.',
        'Add onion, garlic and broccoli. Stir-fry 3 min.',
        'Toss in bell pepper, add soy sauce.',
        'Cook 2 min until veg is crisp-tender. Serve with rice.']},

{id:'pr11',n:'Grilled Chicken Thighs',c:'protein',e:'🍗',t:25,s:4,tags:['gf','hf'],p:30,
 ing:['chicken','garlic','olive oil','lemon','paprika','salt','rosemary'],
 steps:['Mix garlic, olive oil, lemon juice, paprika and rosemary.',
        'Marinate chicken thighs in mixture for 10+ minutes.',
        'Grill or pan-fry skin side down 10 min, flip, cook 10 min more.',
        'Rest 3 min before serving.']},

{id:'pr12',n:'Protein Overnight Oats',c:'protein',e:'🥣',t:5,s:2,tags:['v','gf','hf'],p:16,
 ing:['oats','milk','plain yoghurt','banana','peanut butter','honey'],
 steps:['Mix oats with milk and yoghurt in a jar.',
        'Stir in a tablespoon of peanut butter.',
        'Cover and refrigerate overnight.',
        'Top with sliced banana and drizzle of honey in the morning.']},

{id:'pr13',n:'Chicken & Sweet Potato Bowl',c:'protein',e:'🍠',t:30,s:2,tags:['gf','hf'],p:36,
 ing:['chicken','sweet potatoes','spinach','garlic','olive oil','paprika','lemon'],
 steps:['Roast cubed sweet potato at 200°C for 20 min.',
        'Pan-fry seasoned chicken in olive oil 8 min per side.',
        'Wilt spinach in the same pan with garlic.',
        'Build bowls: sweet potato, chicken, spinach, lemon squeeze.']},

{id:'pr14',n:'Beef & Veg Wraps',c:'protein',e:'🌯',t:15,s:4,tags:['hf'],p:28,
 ing:['ground beef','wraps','onion','garlic','tomatoes','cheese','lettuce'],
 steps:['Brown mince with onion, garlic, salt and pepper.',
        'Warm wraps in a dry pan.',
        'Fill with mince, diced tomatoes, cheese and lettuce.',
        'Fold and serve.']},

{id:'pr15',n:'Egg & Bacon Breakfast Plate',c:'protein',e:'🥓',t:12,s:2,tags:['gf','hf'],p:22,
 ing:['eggs','bacon','tomatoes','butter','salt'],
 steps:['Fry bacon rashers until crispy. Set aside.',
        'Halve tomatoes and fry cut-side down in bacon fat.',
        'Fry or scramble eggs in butter.',
        'Plate bacon, eggs and tomatoes. Season and serve.']},

// ── SA CLASSICS ─────────────────────────────────────────────────────
{id:'sa01',n:'Bobotie',c:'sa',e:'🇿🇦',t:60,s:6,tags:[],p:26,
 ing:['ground beef','bread','milk','eggs','onion','curry powder','dried fruit','almonds','bay leaves','lemon'],
 steps:['Sauté onion and curry powder. Add mince and brown.',
        'Soak bread in milk, squeeze out (keep milk). Crumble into mince with fruit and almonds.',
        'Press into greased dish. Top with egg-and-milk custard mixture.',
        'Bake at 180°C for 35-40 min until set and golden.']},

{id:'sa02',n:'Boerewors Rolls',c:'sa',e:'🌭',t:20,s:4,tags:[],p:22,
 ing:['sausage','bread','onion','canned tomatoes','oil'],
 steps:['Braai or pan-fry boerewors until cooked through.',
        'Fry sliced onion until caramelised.',
        'Add a splash of tomato and simmer for a saucy topping.',
        'Slice bread rolls, fill with boerewors and caramelised onions.']},

{id:'sa03',n:'Pap & Tomato Bredie',c:'sa',e:'🍲',t:45,s:6,tags:['v','gf'],p:6,
 ing:['maize meal','canned tomatoes','onion','oil','garlic','chilli','salt'],
 steps:['Bring salted water to boil (4 cups per 1 cup pap).',
        'Stir in maize meal, cover and cook on low 20 min, stirring occasionally.',
        'Fry onion and garlic until golden. Add chilli, then canned tomatoes.',
        'Simmer tomato bredie 15 min. Serve alongside stiff pap.']},

{id:'sa04',n:'Braai Chicken',c:'sa',e:'🔥',t:45,s:4,tags:['gf'],p:28,
 ing:['chicken','garlic','lemon','olive oil','paprika','salt'],
 steps:['Mix garlic, lemon, olive oil, paprika, salt into a marinade.',
        'Score chicken pieces and rub marinade in well. Rest 30 min.',
        'Braai over medium coals, turning regularly, about 35 min.',
        'Chicken is done when juices run clear.']},

{id:'sa05',n:'Frikkadels',c:'sa',e:'🍖',t:30,s:4,tags:[],p:26,
 ing:['ground beef','bread','onion','eggs','milk','coriander','salt'],
 steps:['Soak bread in milk, squeeze and crumble into mince.',
        'Add grated onion, egg, coriander, salt and pepper. Mix well.',
        'Shape into balls, flatten slightly.',
        'Fry in oil on medium heat, 5 min each side until cooked through.']},

{id:'sa06',n:'Potjiekos',c:'sa',e:'🍲',t:120,s:8,tags:['gf'],p:28,
 ing:['chicken','potatoes','carrots','onion','stock','garlic','squash','beer'],
 steps:['Brown chicken in potjie on coals. Remove.',
        'Fry onion and garlic. Layer vegetables on top — no stirring!',
        'Return chicken on top of veg. Add stock and beer.',
        'Cook covered on medium coals 2 hours. Resist opening the lid.']},

{id:'sa07',n:'Bunny Chow',c:'sa',e:'🍞',t:45,s:4,tags:[],p:22,
 ing:['bread','ground beef','onion','garlic','curry powder','canned tomatoes','potatoes'],
 steps:['Brown mince with onion, garlic and curry powder.',
        'Add potatoes and canned tomatoes. Simmer 25 min.',
        'Hollow out half a loaf of bread from the top.',
        'Fill bread hollow with curry. Top with the bread "lid".']},

{id:'sa08',n:'Snoek Braai',c:'sa',e:'🐟',t:30,s:4,tags:['gf'],p:26,
 ing:['fish','butter','garlic','lemon','apricot jam','chilli','salt'],
 steps:['Mix butter, garlic, lemon and apricot jam into a basting sauce.',
        'Score fish on skin side. Season generously.',
        'Braai flesh side down on grid for 8 min.',
        'Turn, baste generously and cook 10 min more. Baste again.']},

{id:'sa09',n:'Chakalaka',c:'sa',e:'🌶',t:20,s:6,tags:['v','vg','gf'],p:8,
 ing:['onion','bell pepper','carrots','canned tomatoes','chilli','garlic','curry powder','beans'],
 steps:['Fry onion, pepper and carrots in oil until soft.',
        'Add garlic, chilli and curry powder. Stir 1 min.',
        'Add canned tomatoes and beans.',
        'Simmer 10 min. Serve as a relish with pap or braai.']},

{id:'sa10',n:'Yellow Rice',c:'sa',e:'🍚',t:25,s:6,tags:['v','gf'],p:5,
 ing:['rice','dried fruit','turmeric','cinnamon','sugar','butter','salt'],
 steps:['Rinse rice. Bring salted water to boil.',
        'Add turmeric, cinnamon stick, raisins, sugar and butter.',
        'Add rice, stir once, cover and simmer on low 18 min.',
        'Fluff with fork. Lovely alongside bobotie or stew.']},

{id:'sa11',n:'Malva Pudding',c:'sa',e:'🍮',t:45,s:8,tags:['v'],p:6,
 ing:['flour','eggs','sugar','butter','apricot jam','milk','bicarbonate of soda','cream'],
 steps:['Mix sugar, eggs and jam. Add melted butter and milk.',
        'Fold in flour and bicarbonate. Pour into greased dish.',
        'Bake at 180°C for 30-35 min until golden and risen.',
        'Pour warm cream sauce (cream, butter, sugar) over hot pudding.']},

{id:'sa12',n:'Milk Tart',c:'sa',e:'🥧',t:60,s:8,tags:['v'],p:8,
 ing:['flour','butter','eggs','sugar','milk','cream','cinnamon','cornflour'],
 steps:['Make short pastry, line tin, bake blind 15 min.',
        'Heat milk and cream until almost boiling.',
        'Mix egg yolks, sugar, flour, cornflour. Slowly whisk in hot milk.',
        'Return to heat, stir until thick. Pour into pastry. Dust with cinnamon.']},

{id:'sa13',n:'Vetkoek with Mince',c:'sa',e:'🍞',t:30,s:6,tags:[],p:16,
 ing:['flour','yeast','sugar','salt','oil','ground beef','onion','curry powder'],
 steps:['Mix flour, yeast, sugar, salt and warm water into a dough. Rest 30 min.',
        'Fry mince with onion and curry powder for the filling.',
        'Shape dough into balls. Deep-fry in oil until golden and cooked through.',
        'Split open and fill with mince curry.']},

{id:'sa14',n:'Braaibroodjies',c:'sa',e:'🧀',t:15,s:4,tags:['v'],p:12,
 ing:['bread','cheese','tomatoes','onion','butter','chutney'],
 steps:['Butter bread slices generously on outside.',
        'Spread chutney inside. Layer cheese, sliced tomato and raw onion.',
        'Press together firmly.',
        'Braai on grid until bread is toasted and cheese melted.']},

{id:'sa15',n:'Mielie Pap & Chakalaka',c:'sa',e:'🌽',t:30,s:6,tags:['v','gf'],p:6,
 ing:['maize meal','canned tomatoes','onion','bell pepper','beans','curry powder','oil'],
 steps:['Bring 4 cups salted water to boil. Pour in 1 cup pap, stir.',
        'Cover and cook on low 20 min, stirring occasionally until thick.',
        'Fry onion, pepper with curry powder. Add tomatoes and beans.',
        'Simmer 10 min. Serve chakalaka alongside pap.']},

// ── BREAKFAST FOR DINNER ────────────────────────────────────────────
{id:'bk01',n:'Full English Breakfast',c:'breakfast',e:'🍳',t:20,s:2,tags:['gf'],p:20,
 ing:['eggs','bacon','tomatoes','bread','butter','beans'],
 steps:['Fry bacon until crispy. Set aside.',
        'Fry eggs in the bacon fat to your liking.',
        'Halve tomatoes and fry cut side down. Warm baked beans.',
        'Toast bread, butter generously. Plate everything together.']},

{id:'bk02',n:'Fluffy Pancakes',c:'breakfast',e:'🥞',t:20,s:4,tags:['v'],p:8,
 ing:['flour','eggs','milk','butter','sugar','baking powder','banana'],
 steps:['Mix flour, baking powder, sugar and a pinch of salt.',
        'Whisk in eggs and milk until smooth. Add melted butter.',
        'Cook tablespoon-sized rounds on medium heat, flip when bubbles appear.',
        'Serve with sliced banana and golden syrup.']},

{id:'bk03',n:'French Toast',c:'breakfast',e:'🍞',t:15,s:4,tags:['v'],p:10,
 ing:['bread','eggs','milk','butter','cinnamon','sugar'],
 steps:['Whisk eggs, milk, cinnamon and a pinch of sugar.',
        'Dip thick bread slices in mixture, coat both sides.',
        'Fry in butter on medium heat 2-3 min each side until golden.',
        'Dust with icing sugar and serve with sliced fruit.']},

{id:'bk04',n:'Build-Your-Own Omelette',c:'breakfast',e:'🍳',t:15,s:2,tags:['v','gf'],p:14,
 ing:['eggs','cheese','bell pepper','onion','tomatoes','butter','milk'],
 steps:['Dice all fillings and prepare them.',
        'Whisk eggs with milk, salt and pepper.',
        'Melt butter in non-stick pan. Pour in eggs.',
        'When edges set, add fillings to one half, fold and serve.']},

{id:'bk05',n:'Banana Waffles',c:'breakfast',e:'🧇',t:25,s:4,tags:['v'],p:8,
 ing:['flour','eggs','milk','butter','banana','baking powder','honey'],
 steps:['Mash banana into a smooth paste.',
        'Mix with egg, milk and melted butter.',
        'Fold in flour and baking powder until just combined.',
        'Cook in waffle maker until golden. Serve with honey.']},

{id:'bk06',n:'Boerie & Egg Roll',c:'breakfast',e:'🌭',t:15,s:2,tags:[],p:20,
 ing:['sausage','eggs','bread','butter','tomatoes'],
 steps:['Pan-fry boerewors in a little oil until cooked through.',
        'Fry eggs alongside in same pan.',
        'Toast and butter bread rolls.',
        'Fill rolls with boerewors, egg and sliced tomato.']},

{id:'bk07',n:'Eggs Benedict',c:'breakfast',e:'🍳',t:25,s:2,tags:['v'],p:18,
 ing:['eggs','bread','butter','lemon','cream','bacon'],
 steps:['Make a quick hollandaise: whisk egg yolks with lemon juice over gentle heat; beat in butter.',
        'Poach eggs in simmering water with a splash of vinegar.',
        'Fry bacon until crispy. Toast English muffins.',
        'Build: muffin, bacon, egg, hollandaise.']},

{id:'bk08',n:'Smoothie Bowl',c:'breakfast',e:'🍓',t:10,s:2,tags:['v','vg','gf'],p:8,
 ing:['banana','milk','plain yoghurt','honey','oats','fresh fruit'],
 steps:['Blend banana with yoghurt and a splash of milk until thick and smooth.',
        'Pour into bowls — the consistency should be thick enough to eat with a spoon.',
        'Top with oats, fresh fruit and a drizzle of honey.',
        'Eat immediately.']},

{id:'bk09',n:'Baked Beans on Toast',c:'breakfast',e:'🫘',t:10,s:2,tags:['v'],p:10,
 ing:['beans','bread','butter','cheese','salt'],
 steps:['Heat baked beans in a small saucepan with a pinch of salt.',
        'Toast bread until golden and crisp.',
        'Butter toast generously.',
        'Pour hot beans over toast. Top with grated cheese if desired.']},

{id:'bk10',n:'Breakfast Burrito',c:'breakfast',e:'🌯',t:20,s:4,tags:[],p:18,
 ing:['wraps','eggs','bacon','cheese','tomatoes','onion','butter'],
 steps:['Scramble eggs in butter.',
        'Fry bacon until crispy. Sauté diced onion.',
        'Warm wraps in a dry pan.',
        'Fill with scrambled eggs, bacon, onion, tomatoes and cheese. Roll tightly.']},

// ── BUDGET MEALS (under R150 for 4) ────────────────────────────────
{id:'bu01',n:'Samp & Beans',c:'budget',e:'🌽',t:90,s:6,tags:['v','gf'],p:12,
 ing:['dried beans','maize meal','onion','oil','salt'],
 steps:['Soak samp and beans overnight. Drain.',
        'Cover with fresh water, boil until tender (~60 min).',
        'Fry onion until golden, add to pot with salt.',
        'Simmer 15 min until thick and creamy. Serve with chakalaka.']},

{id:'bu02',n:'Red Lentil Dhal',c:'budget',e:'🍲',t:30,s:4,tags:['v','vg','gf'],p:13,
 ing:['lentils','canned tomatoes','onion','garlic','cumin','turmeric','oil'],
 steps:['Fry onion with cumin and turmeric until fragrant.',
        'Add garlic, stir 1 min.',
        'Add lentils and canned tomatoes plus 2 cups water.',
        'Simmer 20 min until lentils dissolve into a thick sauce. Serve with rice or bread.']},

{id:'bu03',n:'Pasta with Tomato Sauce',c:'budget',e:'🍝',t:20,s:4,tags:['v'],p:10,
 ing:['pasta','canned tomatoes','garlic','onion','olive oil','basil','parmesan'],
 steps:['Sauté onion and garlic in olive oil until soft.',
        'Add canned tomatoes, salt, pepper and a pinch of sugar.',
        'Simmer 12 min until thickened.',
        'Toss with al dente pasta, fresh basil and parmesan.']},

{id:'bu04',n:'Hearty Bean Soup',c:'budget',e:'🍵',t:35,s:6,tags:['v','vg','gf'],p:11,
 ing:['beans','onion','garlic','carrots','canned tomatoes','stock','oil'],
 steps:['Fry onion, garlic and carrots in oil until softened.',
        'Add canned tomatoes, beans and stock.',
        'Simmer 20 min. Remove a cup of soup, mash and return for thickness.',
        'Season well and serve with crusty bread.']},

{id:'bu05',n:'Pap with Tomato Gravy',c:'budget',e:'🌽',t:30,s:6,tags:['v','gf'],p:6,
 ing:['maize meal','canned tomatoes','onion','oil','chilli','garlic'],
 steps:['Make pap: boil 4 cups salted water, add 1 cup maize meal.',
        'Cover, cook on lowest heat 20 min, stirring twice.',
        'Fry onion and garlic until golden. Add chilli and canned tomatoes.',
        'Simmer gravy 10 min. Pour over stiff pap.']},

{id:'bu06',n:'Tuna Fishcakes',c:'budget',e:'🐟',t:25,s:4,tags:[],p:22,
 ing:['tuna','potatoes','onion','eggs','flour','oil','lemon'],
 steps:['Boil and mash potatoes.',
        'Mix mashed potato with drained tuna, grated onion and egg.',
        'Shape into patties, dust in flour.',
        'Shallow fry in oil 3 min each side until golden. Serve with lemon.']},

{id:'bu07',n:'Budget Egg Fried Rice',c:'budget',e:'🍳',t:15,s:4,tags:['v','gf'],p:10,
 ing:['rice','eggs','oil','soy sauce','onion','frozen peas'],
 steps:['Use leftover cold rice for best results.',
        'Scramble eggs in hot oil, push to side.',
        'Add rice, frozen peas and diced onion. Stir-fry 3 min.',
        'Splash in soy sauce, toss well and serve hot.']},

{id:'bu08',n:'Bread & Butter Pudding',c:'budget',e:'🍮',t:45,s:6,tags:['v'],p:8,
 ing:['bread','butter','eggs','milk','sugar','cinnamon','dried fruit'],
 steps:['Butter bread slices on both sides. Layer in greased dish with raisins.',
        'Whisk eggs, milk, sugar and cinnamon into custard.',
        'Pour custard over bread. Press down and rest 15 min.',
        'Bake at 180°C for 30-35 min until golden and set.']},

{id:'bu09',n:'Chickpea Tomato Curry',c:'budget',e:'🍛',t:30,s:4,tags:['v','vg','gf'],p:12,
 ing:['beans','canned tomatoes','onion','garlic','curry powder','oil','rice'],
 steps:['Fry onion and garlic until golden.',
        'Add curry powder, stir 1 min.',
        'Add chickpeas and canned tomatoes. Simmer 18 min.',
        'Season well. Serve with rice.']},

{id:'bu10',n:'Oven Chicken Drumsticks & Chips',c:'budget',e:'🍗',t:40,s:4,tags:['gf'],p:26,
 ing:['chicken','potatoes','oil','paprika','garlic','salt'],
 steps:['Preheat oven to 200°C.',
        'Toss potato chips in oil, paprika and salt. Spread on tray.',
        'Season drumsticks with garlic, paprika and salt. Place on same tray.',
        'Roast 35 min, turning chips halfway.']},

// ── LUNCHBOX FRIENDLY ────────────────────────────────────────────────
{id:'lb01',n:'Chicken Mayo Wrap',c:'lunchbox',e:'🌯',t:10,s:2,tags:['hf'],p:28,
 ing:['chicken','wraps','mayonnaise','lettuce','tomatoes','cucumber'],
 steps:['Shred cooked chicken and mix with mayonnaise. Season.',
        'Lay wrap flat, add lettuce, sliced tomato and cucumber.',
        'Top with chicken mayo.',
        'Roll tightly and wrap in foil or cling wrap for lunchbox.']},

{id:'lb02',n:'Cold Pasta Salad',c:'lunchbox',e:'🍝',t:15,s:4,tags:['v'],p:12,
 ing:['pasta','cherry tomatoes','cucumber','feta','olives','olive oil','lemon'],
 steps:['Cook pasta al dente. Rinse with cold water to cool.',
        'Halve cherry tomatoes, dice cucumber.',
        'Combine pasta, tomatoes, cucumber, olives and crumbled feta.',
        'Dress with olive oil and lemon juice. Season well.']},

{id:'lb03',n:'Egg Mayo Sandwich',c:'lunchbox',e:'🥚',t:10,s:2,tags:['v'],p:12,
 ing:['eggs','mayonnaise','bread','lettuce','salt','mustard'],
 steps:['Hard boil eggs (10 min). Cool, peel and chop.',
        'Mix with mayonnaise, a dollop of mustard, salt and pepper.',
        'Spread on bread slices over lettuce.',
        'Press together and cut diagonally.']},

{id:'lb04',n:'Tuna Mayo Bap',c:'lunchbox',e:'🐟',t:10,s:2,tags:[],p:24,
 ing:['tuna','bread','mayonnaise','lemon','cucumber','lettuce'],
 steps:['Drain tuna well. Mix with mayonnaise and a squeeze of lemon.',
        'Season with salt and pepper.',
        'Split bread rolls and layer with lettuce and sliced cucumber.',
        'Fill with tuna mayo.']},

{id:'lb05',n:'Peanut Butter & Banana Wrap',c:'lunchbox',e:'🍌',t:5,s:1,tags:['v','vg'],p:9,
 ing:['wraps','peanut butter','banana','honey'],
 steps:['Spread peanut butter generously over the wrap.',
        'Lay whole or sliced banana in the centre.',
        'Drizzle with honey.',
        'Roll tightly and slice in half.']},

{id:'lb06',n:'Greek Salad Lunchbox',c:'lunchbox',e:'🥗',t:10,s:2,tags:['v','gf'],p:10,
 ing:['tomatoes','cucumber','feta','olives','onion','olive oil'],
 steps:['Dice tomatoes and cucumber into chunks.',
        'Slice red onion thinly.',
        'Combine with pitted olives and crumbled feta.',
        'Dress with olive oil, dried oregano, salt and pepper.']},

{id:'lb07',n:'Rice & Roasted Veg Box',c:'lunchbox',e:'🍱',t:15,s:2,tags:['v','gf'],p:8,
 ing:['rice','sweet potatoes','spinach','olive oil','garlic','lemon'],
 steps:['Cook rice per packet and allow to cool.',
        'Cube sweet potato and microwave or roast until tender.',
        'Wilt spinach with garlic and olive oil.',
        'Layer rice, sweet potato and spinach. Dress with lemon juice.']},

{id:'lb08',n:'Mini Frittata Muffins',c:'lunchbox',e:'🧁',t:30,s:6,tags:['v','gf'],p:14,
 ing:['eggs','cheese','bell pepper','onion','spinach','milk','salt'],
 steps:['Preheat oven to 180°C. Grease a muffin tin.',
        'Dice veg small, wilt spinach.',
        'Whisk eggs with milk, salt and pepper. Stir in veg and cheese.',
        'Pour into muffin moulds. Bake 20-22 min until set and golden.']},

{id:'lb09',n:'Cheesy Quesadilla Wedges',c:'lunchbox',e:'🫓',t:12,s:2,tags:['v'],p:13,
 ing:['wraps','cheese','tomatoes','onion','bell pepper'],
 steps:['Dice tomatoes and pepper finely.',
        'Sprinkle cheese and veg on one tortilla. Top with second.',
        'Cook in a dry pan on medium, 2 min each side until golden.',
        'Cool slightly before cutting into wedges for packing.']},

{id:'lb10',n:'Chickpea Salad Box',c:'lunchbox',e:'🥙',t:10,s:2,tags:['v','vg','gf'],p:11,
 ing:['beans','tomatoes','cucumber','onion','lemon','olive oil','coriander'],
 steps:['Drain and rinse chickpeas.',
        'Dice tomatoes, cucumber and red onion.',
        'Combine chickpeas and veg in a container.',
        'Dress with olive oil, lemon juice, coriander, salt and pepper.']},

// ── CROWD / WEEKEND COOKING ─────────────────────────────────────────
{id:'cr01',n:'Slow-Roast Whole Chicken',c:'crowd',e:'🍗',t:120,s:6,tags:['gf'],p:36,
 ing:['chicken','butter','garlic','lemon','rosemary','salt','potatoes'],
 steps:['Preheat oven to 160°C.',
        'Mix butter, garlic, lemon zest and rosemary. Rub under and over skin.',
        'Place chicken over halved potatoes in roasting tin. Season well.',
        'Roast 1.5 hours, rest 15 min, then carve.']},

{id:'cr02',n:'Classic Lasagne',c:'crowd',e:'🍝',t:90,s:8,tags:[],p:28,
 ing:['ground beef','pasta','canned tomatoes','onion','garlic','cheese','milk','flour','butter'],
 steps:['Make Bolognese: brown mince with onion, garlic and canned tomatoes. Simmer 20 min.',
        'Make béchamel: melt butter, add flour, slowly whisk in milk. Season.',
        'Layer pasta sheets, Bolognese, béchamel, repeat. Top with cheese.',
        'Bake at 180°C for 40-45 min until bubbling and golden.']},

{id:'cr03',n:'Slow-Roast Lamb',c:'crowd',e:'🥩',t:150,s:8,tags:['gf'],p:34,
 ing:['steak','garlic','rosemary','olive oil','lemon','onion','potatoes'],
 steps:['Stab lamb leg all over and insert garlic slices.',
        'Rub with olive oil, lemon, rosemary, salt and pepper.',
        'Roast at 150°C on a bed of onions and potatoes for 2.5 hours.',
        'Rest 20 min before carving.']},

{id:'cr04',n:'Seafood Paella',c:'crowd',e:'🥘',t:50,s:6,tags:['gf'],p:28,
 ing:['rice','fish','onion','garlic','bell pepper','canned tomatoes','paprika','saffron','stock','oil'],
 steps:['Fry onion, garlic and pepper in wide pan until soft.',
        'Add paprika and rice. Stir 2 min.',
        'Pour in stock, canned tomatoes and saffron. Bring to boil.',
        'Arrange fish on top. Simmer uncovered 20 min until liquid is absorbed.']},

{id:'cr05',n:'Homemade Pizza',c:'crowd',e:'🍕',t:60,s:6,tags:['v'],p:13,
 ing:['flour','yeast','canned tomatoes','cheese','onion','bell pepper','olive oil'],
 steps:['Make dough: mix flour, yeast, salt, olive oil and warm water. Knead 8 min. Rest 30 min.',
        'Simmer canned tomatoes with garlic, salt and oregano for sauce.',
        'Roll dough thin. Spread sauce, add toppings and cheese.',
        'Bake at 230°C for 10-12 min until crust is crispy.']},

{id:'cr06',n:'Loaded Nachos',c:'crowd',e:'🌮',t:25,s:6,tags:['v'],p:12,
 ing:['tortilla chips','cheese','canned tomatoes','onion','beans','sour cream','chilli'],
 steps:['Preheat oven to 200°C.',
        'Layer chips in oven dish, top with beans, diced tomato and onion.',
        'Smother with cheese. Bake 10-12 min until cheese bubbles.',
        'Serve with dollops of sour cream and guacamole.']},

{id:'cr07',n:'Build-Your-Own Tacos',c:'crowd',e:'🌮',t:30,s:6,tags:[],p:26,
 ing:['ground beef','wraps','onion','garlic','chilli','cheese','tomatoes','sour cream','lettuce'],
 steps:['Brown mince with onion, garlic, chilli, cumin and salt.',
        'Warm taco shells or wraps in the oven.',
        'Prepare toppings: shredded lettuce, diced tomato, grated cheese.',
        'Let everyone build their own tacos at the table.']},

{id:'cr08',n:'Spaghetti Bolognese',c:'crowd',e:'🍝',t:60,s:6,tags:[],p:26,
 ing:['pasta','ground beef','canned tomatoes','onion','garlic','olive oil','parmesan','basil'],
 steps:['Brown mince in olive oil, breaking up lumps.',
        'Add onion and garlic, fry 3 min.',
        'Add canned tomatoes, salt and a pinch of sugar. Simmer 30 min.',
        'Toss with al dente pasta and fresh basil. Serve with parmesan.']},

{id:'cr09',n:'Sunday Roast Chicken & Veg',c:'crowd',e:'🍗',t:90,s:6,tags:['gf'],p:34,
 ing:['chicken','potatoes','carrots','onion','garlic','butter','stock','rosemary'],
 steps:['Stuff chicken with garlic, butter and rosemary. Season well.',
        'Roast at 190°C for 20 min per 500g plus 20 min.',
        'Add par-boiled potatoes and carrots around chicken for last 40 min.',
        'Rest chicken 15 min. Use pan juices for gravy.']},

{id:'cr10',n:'Slow-Braised BBQ Ribs',c:'crowd',e:'🍖',t:180,s:4,tags:['gf'],p:34,
 ing:['steak','garlic','onion','canned tomatoes','soy sauce','honey','mustard','oil'],
 steps:['Season ribs with salt and pepper. Brown all over in oil.',
        'Mix canned tomatoes, honey, soy sauce, mustard and garlic into BBQ sauce.',
        'Place ribs in dish, pour sauce over. Cover with foil.',
        'Braise at 160°C for 2.5 hours. Uncover last 20 min to caramelise.']}

,

// ── MEDITERRANEAN ────────────────────────────────────────────────────
{id:'md01',n:'Grilled Halloumi & Veg',c:'med',e:'🧀',t:15,s:4,tags:['v','gf'],p:16,
 ing:['halloumi','courgette','bell pepper','olive oil','lemon'],
 steps:['Slice halloumi 1cm thick, courgette lengthways, pepper into strips.',
        'Brush everything with olive oil.',
        'Grill or griddle on high heat 2-3 min each side until charred lines appear.',
        'Squeeze lemon over and serve immediately — halloumi toughens as it cools.']},

{id:'md02',n:'Herb Couscous Salad',c:'med',e:'🥗',t:15,s:4,tags:['v','vg'],p:11,
 ing:['couscous','tomatoes','cucumber','onion','olive oil','lemon','coriander'],
 steps:['Pour boiling water over couscous (equal volumes). Cover and rest 5 min.',
        'Fluff with a fork. Cool 5 min.',
        'Dice tomatoes, cucumber and red onion. Add to couscous.',
        'Dress with olive oil, lemon juice and chopped coriander. Season well.']},

{id:'md03',n:'Baked Aubergine with Feta',c:'med',e:'🍆',t:40,s:4,tags:['v','gf'],p:13,
 ing:['aubergine','canned tomatoes','cheese','garlic','olive oil','basil'],
 steps:['Halve aubergines lengthways, score flesh, brush with olive oil. Roast 20 min at 200°C.',
        'Sauté garlic in olive oil 1 min. Add canned tomatoes. Simmer 8 min.',
        'Spoon tomato sauce over aubergine halves. Top with crumbled feta.',
        'Return to oven 10 min until golden. Scatter fresh basil.']},

{id:'md04',n:'Tahini Roasted Vegetables',c:'med',e:'🥦',t:35,s:4,tags:['v','vg','gf'],p:12,
 ing:['tahini','sweet potatoes','broccoli','garlic','lemon','olive oil'],
 steps:['Roast cubed sweet potato and broccoli florets at 200°C for 25 min.',
        'Whisk tahini with lemon juice, garlic, 3 tbsp water and a pinch of salt until pourable.',
        'Drizzle tahini sauce over hot vegetables.',
        'Serve as a side or over rice or couscous.']},

{id:'md05',n:'Mediterranean Quinoa Bowl',c:'med',e:'🥗',t:25,s:4,tags:['v','gf'],p:14,
 ing:['quinoa','tomatoes','cucumber','cheese','olives','olive oil','lemon'],
 steps:['Rinse quinoa. Simmer in 2x water 15 min until absorbed. Fluff and cool.',
        'Dice tomatoes and cucumber. Slice olives.',
        'Combine quinoa, veg and pitted olives in a bowl.',
        'Dress with olive oil and lemon juice. Top with crumbled feta.']},

{id:'md06',n:'Aubergine & Chickpea Stew',c:'med',e:'🍲',t:35,s:4,tags:['v','vg','gf'],p:12,
 ing:['aubergine','beans','canned tomatoes','onion','garlic','cumin','oil'],
 steps:['Cut aubergine into 2cm cubes. Fry in oil until golden. Remove.',
        'Fry onion and garlic until soft. Add cumin, stir 30 sec.',
        'Add chickpeas, canned tomatoes and aubergine. Season.',
        'Simmer 20 min until thick. Serve with bread or couscous.']},

{id:'md07',n:'Halloumi & Roasted Veg Wraps',c:'med',e:'🌯',t:20,s:4,tags:['v'],p:15,
 ing:['halloumi','wraps','bell pepper','onion','tomatoes','lettuce','lemon'],
 steps:['Slice and griddle halloumi 2 min each side until golden.',
        'Thinly slice pepper and onion and griddle 3 min.',
        'Warm wraps in a dry pan.',
        'Fill wraps with halloumi, veg, fresh tomatoes and lettuce. Squeeze lemon.']},

{id:'md08',n:'Moroccan Spiced Roasted Veg',c:'med',e:'🫒',t:40,s:4,tags:['v','vg','gf'],p:10,
 ing:['sweet potatoes','carrots','onion','beans','ras el hanout','olive oil','coriander'],
 steps:['Preheat oven to 200°C.',
        'Toss cubed sweet potato, carrots and onion with ras el hanout and olive oil.',
        'Roast 30 min until caramelised, turning halfway.',
        'Stir in drained chickpeas for last 10 min. Top with fresh coriander.']},

{id:'md09',n:'Tahini Lemon Salad',c:'med',e:'🥗',t:10,s:4,tags:['v','vg','gf'],p:10,
 ing:['tahini','lemon','garlic','lettuce','cucumber','tomatoes','olives'],
 steps:['Whisk tahini, lemon juice and minced garlic with 4 tbsp water until smooth.',
        'Season dressing with salt and pepper.',
        'Roughly chop lettuce, dice cucumber and tomatoes.',
        'Toss salad with dressing and scatter olives over the top.']},

{id:'md10',n:'Couscous-Stuffed Peppers',c:'med',e:'🫑',t:40,s:4,tags:['v'],p:13,
 ing:['couscous','bell pepper','canned tomatoes','cheese','onion','garlic','olive oil'],
 steps:['Halve and deseed peppers. Brush with oil and roast cut-side up at 180°C for 15 min.',
        'Cook couscous in vegetable stock. Fry onion and garlic, combine with couscous.',
        'Stir in canned tomatoes and season. Spoon filling into peppers.',
        'Top with cheese. Bake a further 15 min until melted and golden.']},

{id:'md11',n:'Halloumi & Egg Breakfast',c:'med',e:'🧀',t:15,s:2,tags:['v','gf'],p:18,
 ing:['halloumi','eggs','tomatoes','olive oil','lemon'],
 steps:['Slice halloumi 1cm thick.',
        'Fry in a dry non-stick pan on medium-high until golden on both sides.',
        'Halve tomatoes and fry cut-side down in olive oil until caramelised.',
        'Fry or poach eggs alongside. Plate with a squeeze of lemon.']},

{id:'md12',n:'Quinoa Breakfast Bowl',c:'med',e:'🥣',t:20,s:2,tags:['v','gf'],p:10,
 ing:['quinoa','milk','banana','honey','cinnamon'],
 steps:['Simmer quinoa in milk (2:1 ratio) over low heat for 15 min, stirring often.',
        'Add a pinch of cinnamon and a drizzle of honey.',
        'Cook until creamy — add a splash more milk if needed.',
        'Serve topped with sliced banana and an extra drizzle of honey.']},

{id:'md13',n:'Grilled Aubergine Flatbread',c:'med',e:'🥪',t:15,s:2,tags:['v','vg'],p:11,
 ing:['aubergine','pita bread','tomatoes','olive oil','garlic','basil'],
 steps:['Slice aubergine into 1cm rounds. Brush with garlic-infused olive oil.',
        'Grill or griddle 3 min each side until soft and charred.',
        'Warm pita bread in the oven.',
        'Layer grilled aubergine and sliced tomatoes on pita. Scatter fresh basil.']},

// ── ASIAN KITCHEN ────────────────────────────────────────────────────
{id:'as01',n:'Crispy Tofu Stir-Fry',c:'asian',e:'🥢',t:20,s:4,tags:['v','vg','gf'],p:12,
 ing:['tofu','broccoli','bell pepper','soy sauce','garlic','sesame oil','oil'],
 steps:['Press tofu dry with paper towel. Cube and pan-fry in oil until crispy on all sides.',
        'Remove tofu. Stir-fry garlic, broccoli and pepper 4 min.',
        'Return tofu, add soy sauce and sesame oil.',
        'Toss to coat and serve over rice immediately.']},

{id:'as02',n:'Miso Soup with Tofu & Nori',c:'asian',e:'🍵',t:15,s:4,tags:['v','vg','gf'],p:8,
 ing:['miso','tofu','nori','spring onions','stock'],
 steps:['Bring vegetable stock to a gentle simmer (do not boil).',
        'Dissolve miso paste in a ladle of warm stock, then stir back into pot.',
        'Dice firm tofu and add to pot. Simmer 3 min.',
        'Serve topped with sliced spring onions and torn nori sheets.']},

{id:'as03',n:'Thai Red Curry',c:'asian',e:'🍛',t:30,s:4,tags:['v','vg','gf'],p:12,
 ing:['red curry paste','coconut milk','sweet potatoes','broccoli','beans','rice','oil'],
 steps:['Fry red curry paste in oil 1 min until fragrant.',
        'Add coconut milk, diced sweet potato and chickpeas.',
        'Simmer 15 min until sweet potato is tender. Add broccoli last 5 min.',
        'Serve over steamed rice. Adjust heat with more or less curry paste.']},

{id:'as04',n:'Edamame & Sesame Rice Bowl',c:'asian',e:'🍱',t:15,s:2,tags:['v','vg','gf'],p:13,
 ing:['rice','edamame','avocado','soy sauce','sesame oil','spring onions','nori'],
 steps:['Cook rice per packet.',
        'Steam or microwave edamame until bright green and tender.',
        'Slice avocado. Shred or tear nori.',
        'Build bowls: rice, edamame, avocado. Dress with soy sauce and sesame oil. Top with spring onions and nori.']},

{id:'as05',n:'Soba Noodle & Edamame Salad',c:'asian',e:'🍜',t:15,s:4,tags:['v','vg'],p:12,
 ing:['noodles','edamame','cucumber','soy sauce','sesame oil','spring onions','garlic'],
 steps:['Cook soba noodles per packet. Rinse under cold water to stop cooking.',
        'Steam edamame. Julienne or thinly slice cucumber.',
        'Whisk soy sauce, sesame oil and minced garlic into a dressing.',
        'Toss noodles, edamame and cucumber in dressing. Top with spring onions.']},

{id:'as06',n:'Tofu Scramble on Toast',c:'asian',e:'🍳',t:15,s:4,tags:['v','vg','df'],p:12,
 ing:['tofu','turmeric','onion','bell pepper','soy sauce','oil','bread'],
 steps:['Crumble firm tofu into a bowl. It should resemble scrambled egg.',
        'Fry diced onion and pepper in oil 3 min.',
        'Add crumbled tofu, turmeric and soy sauce. Stir-fry 5 min until golden.',
        'Serve on toasted bread. Season with salt and pepper.']},

{id:'as07',n:'Chia Seed Pudding',c:'asian',e:'🥣',t:5,s:2,tags:['v','gf'],p:8,
 ing:['chia seeds','coconut milk','honey','banana'],
 steps:['Mix chia seeds with coconut milk and honey. Stir thoroughly.',
        'Leave 5 min, stir again to break up any clumps.',
        'Cover and refrigerate overnight (or at least 2 hours) until thick and creamy.',
        'Serve topped with sliced banana and extra honey.']},

{id:'as08',n:'Tofu & Veg Green Curry',c:'asian',e:'🍛',t:25,s:4,tags:['v','vg','gf'],p:11,
 ing:['tofu','red curry paste','coconut milk','courgette','bell pepper','spring onions','rice'],
 steps:['Press and cube tofu. Lightly fry until golden. Remove.',
        'Fry curry paste in the same pan 1 min.',
        'Pour in coconut milk. Add diced courgette and pepper. Simmer 10 min.',
        'Return tofu. Serve over rice topped with sliced spring onions.']},

{id:'as09',n:'Tamarind Lentil Soup',c:'asian',e:'🍜',t:30,s:4,tags:['v','vg','gf'],p:12,
 ing:['lentils','tamarind','onion','garlic','canned tomatoes','cumin','oil'],
 steps:['Fry onion, garlic and cumin in oil until fragrant.',
        'Add lentils, canned tomatoes and 4 cups water.',
        'Simmer 20 min until lentils are completely soft.',
        'Stir in tamarind paste, season with salt. Adjust sourness to taste.']}

]; // end FF_RECIPES
